# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S0PkukoO1RirUT24s7q0ErmWzZTIaS9F
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from datetime import datetime, timedelta
import pickle
import json
import warnings
warnings.filterwarnings('ignore')

from google.colab import files

uploaded = files.upload()

print("=" * 60)
print("  HALCHAL INDUSTRIES - ML PRICING ENGINE")
print("=" * 60)

df = pd.read_csv("Halchal_Industries_Final_Dataset.csv")
print(f"\n✅ Dataset Loaded: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"   Pipe Types  : {df['Pipe_Type'].unique().tolist()}")
print(f"   Regions     : {df['Region'].unique().tolist()}")
print(f"   Year Range  : {df['Year'].min()} to {df['Year'].max()}")

encoders = {}
categorical_cols = ['Pipe_Type', 'Region', 'Season']

df_encoded = df.copy()
for col in categorical_cols:
    le = LabelEncoder()
    df_encoded[col + '_enc'] = le.fit_transform(df[col])
    encoders[col] = le
    print(f"   Encoded [{col}]: {dict(zip(le.classes_, le.transform(le.classes_)))}")

feature_cols = [
    'Pipe_Type_enc',
    'Region_enc',
    'Season_enc',
    'Month',
    'Year',
    'Base_Price',
    'Prev_Month_Sales',
    'Govt_Subsidy_Active'
]
target_col = 'Quantity_Sold'

X = df_encoded[feature_cols]
y = df_encoded[target_col]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"\n📊 Train size: {len(X_train)}  |  Test size: {len(X_test)}")

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(f"\n📊 Train size: {len(X_train)}  |  Test size: {len(X_test)}")

y_pred = rf_model.predict(X_test)

mae  = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2   = r2_score(y_test, y_pred)

print(f"\n📈 MODEL PERFORMANCE:")
print(f"   MAE  (Mean Absolute Error)  : {mae:.2f} units")
print(f"   RMSE (Root Mean Sq. Error)  : {rmse:.2f} units")
print(f"   R2   (Accuracy Score)       : {r2:.4f}  ({r2*100:.2f}%)")

importance_df = pd.DataFrame({
    'Feature': feature_cols,
    'Importance': rf_model.feature_importances_
}).sort_values('Importance', ascending=False)

print(f"\n🔍 FEATURE IMPORTANCE:")
for _, row in importance_df.iterrows():
    bar = "█" * int(row['Importance'] * 40)
    print(f"   {row['Feature']:<25} {row['Importance']:.4f}  {bar}")

avg_demand_by_pipe = df.groupby('Pipe_Type')['Quantity_Sold'].mean().to_dict()
overall_avg_demand = df['Quantity_Sold'].mean()

print(f"\n📦 AVERAGE DEMAND BY PIPE TYPE:")
for pipe, avg in avg_demand_by_pipe.items():
    print(f"   {pipe:<20}: {avg:.1f} units/month")
print(f"   {'Overall Average':<20}: {overall_avg_demand:.1f} units/month")

REGION_FACTORS = {
    'Pune'       : 1.03,
    'Nashik'     : 1.02,
    'Aurangabad' : 1.01,
    'Nagpur'     : 1.04,
    'Kolhapur'   : 0.99,
    'Amravati'   : 1.00,
    'Jalgaon'    : 1.01,
    'Solapur'    : 1.00,
}

# Pricing engine parameters
ALPHA = 0.2   # demand weight
BETA  = 0.15  # competitor weight

# Base prices per pipe type (admin maintained)
BASE_PRICES = {
    '16mm Inline' : 1150,
    '16mm Online' : 1400,
    '20mm Inline' : 1450,
    '20mm Online' : 1600,
}

# Competitor prices (admin updates weekly)
COMPETITOR_PRICES = {
    '16mm Inline' : 1214,
    '16mm Online' : 1380,
    '20mm Inline' : 1500,
    '20mm Online' : 1650,
}

# Month to Season mapping
def get_season(month):
    if month in [6, 7, 8, 9]:    return 'Kharif'
    elif month in [10, 11, 12, 1]: return 'Rabi'
    else:                          return 'Summer'

def get_quantity_factor(quantity):
    if quantity > 2000:   return 0.92   # 8% discount
    elif quantity > 1000: return 0.95   # 5% discount
    elif quantity > 500:  return 0.97   # 3% discount
    else:                 return 1.00   # no discount

def predict_demand(pipe_type, region, season, month, year,
                   base_price, prev_month_sales, govt_subsidy):
    """Predict demand using trained Random Forest model."""
    pipe_enc   = encoders['Pipe_Type'].transform([pipe_type])[0]
    region_enc = encoders['Region'].transform([region])[0]
    season_enc = encoders['Season'].transform([season])[0]

    features = pd.DataFrame([[
        pipe_enc, region_enc, season_enc,
        month, year, base_price,
        prev_month_sales, govt_subsidy
    ]], columns=feature_cols)

    return rf_model.predict(features)[0]

def calculate_weekly_price(pipe_type, region, month, year,
                            prev_month_sales=450, govt_subsidy=1):
    season           = get_season(month)
    base_price       = BASE_PRICES[pipe_type]
    competitor_price = COMPETITOR_PRICES[pipe_type]

    predicted_demand = predict_demand(
        pipe_type, region, season, month, year,
        base_price, prev_month_sales, govt_subsidy
    )

    avg_demand        = avg_demand_by_pipe.get(pipe_type, overall_avg_demand)
    demand_factor     = 1 + ALPHA * (predicted_demand / avg_demand)
    competitor_factor = 1 - BETA * ((competitor_price - base_price) / base_price)
    r_factor          = REGION_FACTORS.get(region, 1.00)
    weekly_price      = base_price * demand_factor * competitor_factor * r_factor

    return {
        "pipe_type"         : pipe_type,
        "region"            : region,
        "season"            : season,
        "month"             : month,
        "year"              : year,
        "base_price"        : round(float(base_price), 2),
        "competitor_price"  : round(float(competitor_price), 2),
        "predicted_demand"  : round(float(predicted_demand), 1),
        "avg_demand"        : round(float(avg_demand), 1),
        "demand_factor"     : round(float(demand_factor), 4),
        "competitor_factor" : round(float(competitor_factor), 4),
        "region_factor"     : round(float(r_factor), 2),
        "weekly_price"      : round(float(weekly_price), 2),
        "status"            : "PENDING_ADMIN_APPROVAL"
    }

def calculate_order_price(weekly_approved_price, customer_quantity):
    qty_factor  = get_quantity_factor(customer_quantity)
    final_price = weekly_approved_price * qty_factor
    return {
        "weekly_approved_price" : round(weekly_approved_price, 2),
        "customer_quantity"     : customer_quantity,
        "quantity_factor"       : qty_factor,
        "discount_percent"      : round((1 - qty_factor) * 100, 1),
        "final_order_price"     : round(final_price, 2)
    }

def generate_weekly_batch(month, year, govt_subsidy=1, prev_month_sales=450):
    all_pipes   = list(BASE_PRICES.keys())
    all_regions = list(REGION_FACTORS.keys())

    today      = datetime.now()
    days_ahead = 0 - today.weekday()
    if days_ahead <= 0:
        days_ahead += 7
    week_start = (today + timedelta(days=days_ahead)).strftime('%Y-%m-%d')
    week_end   = (today + timedelta(days=days_ahead + 6)).strftime('%Y-%m-%d')

    prices = []
    for pipe in all_pipes:
        for region in all_regions:
            entry = calculate_weekly_price(
                pipe, region, month, year,
                prev_month_sales, govt_subsidy
            )
            prices.append(entry)

    return {
        "batch_id"           : f"WEEK-{year}-{month:02d}-{week_start}",
        "week_start"         : week_start,
        "week_end"           : week_end,
        "generated_at"       : datetime.now().isoformat(),
        "month"              : month,
        "year"               : year,
        "season"             : get_season(month),
        "govt_subsidy"       : bool(govt_subsidy),
        "total_combinations" : len(prices),
        "status"             : "PENDING_ADMIN_APPROVAL",
        "approved_by"        : None,
        "approved_at"        : None,
        "prices"             : prices
    }

print("\n" + "=" * 60)
print("  WEEKLY BATCH PRICING - DEMO RUN")
print("  (Month: June 2025 | Season: Kharif | Subsidy: ON)")
print("=" * 60)

batch = generate_weekly_batch(month=6, year=2025, govt_subsidy=1)

print(f"\n  Batch ID      : {batch['batch_id']}")
print(f"  Week Window   : {batch['week_start']}  to  {batch['week_end']}")
print(f"  Season        : {batch['season']}")
print(f"  Govt Subsidy  : {'Active' if batch['govt_subsidy'] else 'Inactive'}")
print(f"  Total Rows    : {batch['total_combinations']} (4 pipes x 9 regions)")
print(f"  Status        : {batch['status']}")

print(f"\n{'─'*100}")
print(f"  {'Pipe Type':<16} {'Region':<14} {'Base':>6} {'Comp':>6} {'Pred.Dem':>9} {'D.Factor':>9} {'C.Factor':>9} {'R.Fac':>6} {'Rec.Price':>10}")
print(f"{'─'*100}")

for p in batch['prices']:
    print(f"  {p['pipe_type']:<16} {p['region']:<14} "
          f"Rs{p['base_price']:>5} Rs{p['competitor_price']:>5} "
          f"{p['predicted_demand']:>9.1f} "
          f"{p['demand_factor']:>9.4f} "
          f"{p['competitor_factor']:>9.4f} "
          f"{p['region_factor']:>6.2f} "
          f"Rs{p['weekly_price']:>9.2f}")

print(f"{'─'*100}")

print(f"\n{'='*60}")
print(f"  ORDER-TIME PRICING")
print(f"  (Quantity Discount on Admin-Approved Weekly Price)")
print(f"{'='*60}")

# Get approved weekly price for 16mm Inline in Pune
approved_price = next(
    p['weekly_price'] for p in batch['prices']
    if p['pipe_type'] == '16mm Inline' and p['region'] == 'Pune'
)

demo_orders = [
    ("Customer A", 300,  "Small farmer"),
    ("Customer B", 700,  "Medium dealer"),
    ("Customer C", 1200, "Large dealer"),
    ("Customer D", 2500, "Bulk buyer"),
]

print(f"\n  Product  : 16mm Inline | Region : Pune")
print(f"  Admin-Approved Weekly Price : Rs{approved_price:.2f}")
print(f"\n  {'Customer':<14} {'Qty':>6}  {'Type':<15} {'Discount':>9}  {'Final Price':>12}")
print(f"  {'─'*58}")

for name, qty, label in demo_orders:
    order = calculate_order_price(approved_price, qty)
    print(f"  {name:<14} {qty:>6}  {label:<15} "
          f"{order['discount_percent']:>8.1f}%  "
          f"Rs{order['final_order_price']:>10.2f}")

with open("weekly_price_batch.json", "w") as f:
    json.dump(batch, f, indent=2)

with open("rf_demand_model.pkl", "wb") as f:
    pickle.dump(rf_model, f)

with open("label_encoders.pkl", "wb") as f:
    pickle.dump(encoders, f)

with open("avg_demand.json", "w") as f:
    json.dump({"by_pipe_type": avg_demand_by_pipe, "overall": overall_avg_demand}, f, indent=2)

with open("region_factors.json", "w") as f:
    json.dump(REGION_FACTORS, f, indent=2)

with open("base_prices.json", "w") as f:
    json.dump(BASE_PRICES, f, indent=2)

print(f"\n\n{'='*60}")
print("  SAVED FILES")
print(f"{'='*60}")
print("  rf_demand_model.pkl      → Trained Random Forest model")
print("  label_encoders.pkl       → Label encoders for categories")
print("  avg_demand.json          → Average demand per pipe type")
print("  region_factors.json      → Region multipliers")
print("  base_prices.json         → Product base prices")
print("  weekly_price_batch.json  → This week's price table (→ MongoDB)")
print("\n✅ ML Engine complete. Ready for Node.js backend.\n")